// =========================
// Songs Data
// =========================

const songs = [
    {
        id: 1,
        title: 'Barbie Girl',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/1-Barbie Girl-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '3:59',
        playlist: 'Mirchi',
    },
    {
        id: 2,
        title: 'Darlingey',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/2-Darlingey-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '3:44',
        playlist: 'Mirchi',
    },
    {
        id: 3,
        title: 'Idhedho Bagundhe',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/3-Idhedho Bagundhe-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '4:28',
        playlist: 'Mirchi',
    },
    {
        id: 4,
        title: 'Mirchi',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/4-Mirchi-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '1:25',
        playlist: 'Mirchi',
    },
    {
        id: 5,
        title: 'Pandagala',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/6-Pandagala-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '4:53',
        playlist: 'Mirchi',
    },
    {
        id: 6,
        title: 'Yahoon Yahoon',
        artist: 'Devi Sri Prasad',
        songName: 'media/audio/7-Yahoon Yahoon-SenSongsMp3.Co.mp3',
        image: 'media/song-images/mirchi.jpg',
        duration: '4:42',
        playlist: 'Mirchi',
    },
    {
        id: 7,
        title: 'A Vachi B Pai',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/A Vachi B Pai-SenSongsMp3.Co.mp3',
        image: 'media/song-images/chatrapathi.jpg',
        duration: '4:45',
        playlist: 'Chatrapathi',
    },
    {
        id: 8,
        title: 'Agni Skalana',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Agni Skalana-SenSongsMp3.Co.mp3',
        image: 'media/song-images/chatrapathi.jpg',
        duration: '3:11',
        playlist: 'Chatrapathi',
    },
    {
        id: 9,
        title: 'Gundu Sudhi',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Gundu Sudhi-SenSongsMp3.Co.mp3',
        image: 'media/song-images/chatrapathi.jpg',
        duration: '4:18',
        playlist: 'Chatrapathi',
    },
    {
        id: 10,
        title: 'Summamma Suriya',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Summama Suriya-SenSongsMp3.Co.mp3',
        image: 'media/song-images/chatrapathi.jpg',
        duration: '4:40',
        playlist: 'Chatrapathi',
    },
    {
        id: 11,
        title: 'Pournami Flute',
        artist: 'DSP',
        songName: 'media/audio/Flute Music-SenSongsMp3.Co.mp3',
        image: 'media/song-images/pournami.jpg',
        duration: '2:09',
        playlist: 'Pournami',
    },
    {
        id: 12,
        title: 'Yevaro Raavali',
        artist: 'DSP',
        songName: 'media/audio/Yevaro Raavali-SenSongsMp3.Co.mp3',
        image: 'media/song-images/pournami.jpg',
        duration: '2:54',
        playlist: 'Pournami',
    },
    {
        id: 13,
        title: 'Jeeva Nadhi',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Jeva Nadhi-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '1:37',
        playlist: 'Bahubali 1',
    },
    {
        id: 14,
        title: 'Mamatala Thalli',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Mamatala Talli-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '3:46',
        playlist: 'Bahubali 1',
    },
    {
        id: 15,
        title: 'Manohari',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Manohari-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '3:34',
        playlist: 'Bahubali 1',
    },
    {
        id: 16,
        title: 'Nippule Swasaga',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Nippulaa Swasa Ga-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '3:08',
        playlist: 'Bahubali 1',
    },
    {
        id: 17,
        title: 'Paccha Bottesina',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Pacha Bottasi-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '4:16',
        playlist: 'Bahubali 1',
    },
    {
        id: 18,
        title: 'Sivuni Aana',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Sivuni Aana-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '3:14',
        playlist: 'Bahubali 1',
    },
    {
        id: 19,
        title: 'Sooreede',
        artist: 'Ravi Basrur',
        songName: 'media/audio/Sooreede.mp3',
        image: 'media/song-images/salaar.jpg',
        duration: '3:20',
        playlist: 'Salaar',
    },
    {
        id: 20,
        title: 'Sound of Salaar',
        artist: 'Ravi Basrur',
        songName: 'media/audio/Sound of Salaar.mp3',
        image: 'media/song-images/salaar.jpg',
        duration: '2:56',
        playlist: 'Salaar',
    },
    {
        id: 21,
        title: 'Prathi Gadhalo',
        artist: 'Ravi Basrur',
        songName: 'media/audio/Prathi Kadalo.mp3',
        image: 'media/song-images/salaar.jpg',
        duration: '3:03',
        playlist: 'Salaar',
    },
    {
        id: 22,
        title: 'Aaru Sethulunnaa',
        artist: 'Ravi Basrur',
        songName: 'media/audio/Aaru Sethulunnaa.mp3',
        image: 'media/song-images/salaar.jpg',
        duration: '1:37',
        playlist: 'Salaar',
    },
    {
        id: 23,
        title: 'Dhivara',
        artist: 'M. M. Keeravani',
        songName: 'media/audio/Dhivara-SenSongsMp3.Co.mp3',
        image: 'media/song-images/bahubali.jpg',
        duration: '5:25',
        playlist: 'Bahubali 1',
    },
    {
        id: 24,
        title: 'Muvvala Navvakala',
        artist: 'DSP',
        songName: 'media/audio/Muvvala Navvakala-SenSongsMp3.Co.mp3',
        image: 'media/song-images/pournami.jpg',
        duration: '5:09',
        playlist: 'Pournami',
    },
];

let filteredSongs = [...songs];